### ISSUE TITLE
Validation of MCBlockReferences against related MC2SCAggregatedTransactions

### ISSUE THREAD

**Issue by albertog78** [ZencashOfficial/Sidechains-SDK#29]
Before applying to the state a SidechainBlock, beyond the semantic validity check of txs, we should also enforce the following:
* Number of MCBlockReferences = number of MC2SCAggregatedTransactions
* For each MCBlockReference check entry hash in SCMap = hash of MC2SCAggregatedTransactions
* remove such check in SCBlock semantic validity used by history (we will just verify PoW and Block hash)

**Comment by i-Alex** [comment]
Done
