### ISSUE TITLE
Optimize withdrawal requests epoch storage

### ISSUE THREAD

**Issue by albertog78** [ZencashOfficial/Sidechains-SDK#73]
Instead of keeping track of all the withdrawal requests of all the epochs we can just keep track of previous epoch withdrawal requests (these are going to be used for creating the certificate) and current epoch withdrawal requests.

**Comment by i-Alex** [comment]
Additional:
1. Move the method `getWithdrawalRequests` from [SidechainStateReader](https://github.com/ZencashOfficial/Sidechains-SDK/blob/dev/sdk/src/main/java/com/horizen/state/SidechainStateReader.java#L10) into [NodeState](https://github.com/ZencashOfficial/Sidechains-SDK/blob/dev/sdk/src/main/java/com/horizen/node/NodeState.java#L5). Also the signature for the method should be changed according to the main issue description changes.
2. Update API Unit tests for the following requests: `SidechainTransactionApiRoute -> withdrawCoins | createRegularTransactionSimplified | createRegularTransaction`

**Comment by i-Alex** [comment]
Done.
