### ISSUE TITLE
Forger boxes eligibility evaluation optimization

### ISSUE THREAD

**Issue by albertog78** [ZencashOfficial/Sidechains-SDK#99]
Considering that a single node can be delegated with several forger boxes we should optimize the lookup for an eligible forger box for a particular slot.
A possible optimization will be to directly return the VRF output hash during proof creation to avoid for each forger box to calculate the proof, validate it again and then extract the output hash to be able to verify eligibility considering the box relative stake.

**Comment by i-Alex** [comment]
Done.
Note: account based delegation is in progress.
